server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlite:simcii.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        #  ELIMINA esta línea:
        # connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider